development:
  adapter: postgresql
  encoding: utf8
  database: your_rails_project
  pool: 5
  username: <username>
  password: <password>
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: your_rails_project
  pool: 5
  username: <username>
  password: <password>
  host: localhost
  port: 5432
