development: &default
  adapter: postgresql
  encoding: utf8
  database: your_rails_project_development
  pool: 5
  username: <username>
  password: <password>
  host: localhost
  port: 5432

test:
  <<: *default
  database: your_rails_project_test
